### PR TITLE
35 separate data and training config files

### PR DESCRIPTION
**Pull request by maho3**
Some refactoring and reorganization of the data loaders and runner objects. Changes:

- Moved inference/loaders.py to its own subdirectory and added `from_config` functions for all loaders. These from_config function naturally takes a `stage' parameter from which one can dynamically set to e.g. train or val
- Separated data and inference configurations for all examples and organized the examples/configs folder
- Hotfixed some bugs in quijote_MDN.yaml
- Moved some of our generic object loaders (e.g. SBIRunner.load_object) into a new subdirectory called utils, for general use.

### CODE REVIEW

**Comment by DeaglanBartlett** [comment]
Nice! There are just a few things that need fixing

installation:
- Add pip as a conda dependency
- "torch" package not found by conda
- Before fourth step of install.md need to clone and cd back to this repo

Example inference:
- Only 'plot_single_posterior.jpg' is produced in this example. Given that the quijote example produces three other diagnostics, it would be nice if this example did too

Quijote example:
- Quijote example states data should be in ili-wg/data but this should be changed to ltu-ili-data
- Change cfgtrain to cfginfer on line 25 of quijote_inference.py

notebook/compare_summaries.ipynb
- File paths are incorrect for yml files or are user-specific ('/n/holystore01/LABS/itc_lab/Users/ccuestalazaro/ili_summaries/summaries/posteriors/'). These should be corrected

**Comment by DeaglanBartlett** [comment]
Just a few more things in INSTALL.md:

- According to the pip instructions, after step 3 you are in the repository ltu-ili/ili-summarizer. Therefore step 4 should start with `cd ..` and not `cd ../ltu-ili`
- Step 6 of the conda installation should begin with `cd ..` (like above)
- The path for the final example is incorrect. Instead of configs/quijote_MDN.yaml it should be configs/infer/quijote_MDN.yaml

**Comment by maho3** [comment]
Thanks for catching this. ili-summarizer should not be cloned into the ltu-ili/ directory, but instead into the same level as ltu-ili. I've cleared that up as well as removed some unnecessary back-and-forth cd'ing.

**Comment by DeaglanBartlett** [comment]
Thanks for changing this. One final thing: now for the installation tests, I think you need to change `cd examples` to `cd ltu-ili/examples` as you aren't in the ltu-ili repository at this point

**Review by DeaglanBartlett — APPROVED** [review]

**Pull request merged**
