### PR TITLE
111 make custom iliutilsdistributions

### PR DESCRIPTION
**Pull request by maho3**
This adds two new files, `ili.utils.distributions_pt.py` and `ili.utils.distributions_tf.py`, which wrap pytorch and pydelfi distributions, respectively, to make them more amenable to our configurations.

Now, users can simply go:
```
prior = ili.utils.Uniform(low=[0, 0, 0], high=[1, 1, 1], device=device)  # Uniform distribution
## OR
prior = ili.utils.IndependentNormal(loc=[0,0,0], scale=[1,1,1])  # Standard normal distribution
```
to get an appropriate prior distribution. The change is the same in the yaml configs.

Features:
- `distributions_pt.py` or `distributions_tf.py` are dynamically loaded dependent on the backend. Everything is then imported directly into `ili.utils`
- `distributions_pt.py` wraps all continuous, univariate distributions available in `torch.distributions` with an Independent version. It also preloads several multivariate distributions, so they can be accessed with `ili.utils`
- All changes have been propagated to all example configs, the tests, and the tutorial notebook.

### CODE REVIEW

**Review by DeaglanBartlett — CHANGES_REQUESTED** [review]
Nice work! Before approval, I think that the tests could be made a little more extended for these changes. In particular:

- `ili.utils.distributions_tf.IndependentNormal` currently is not used in any of the tests
- All distributions used in the tests are independent. I can't anticipate there being a problem when using a dependent distribution, but it should be simple to add so would probably be worth putting in one of the tests.

**Comment by maho3** [comment]
Added designated prior tests in both pydelfi and sbi. Also, I added a custom TruncatedNormal distribution in sbi, to mirror that of pydelfi and to show how one can make a custom pytorch distribution.

**Comment by DeaglanBartlett** [comment]
Thank you for adding these. Perhaps I missed it last time, but given that you've added `Dirichlet` and `LowRankMultivariateNormal` to `ili.utils.distributions_pt`, these should also be included in the unit tests. It would also be good to see unit tests for all the methods of the classes introduced in `ili.utils.distributions_pt` and `ili.utils.distributions_tf`

**Comment by maho3** [comment]
Ready for review again!

**Review by DeaglanBartlett — APPROVED** [review]

**Pull request merged**
